theme: jekyll-theme-cayman
# setup
title: Ben Hemingway
description: Senior Economist CEFER, Bank of Lithuania
baseurl: ""

# repository
repository: benhemingway/benhemingway.github.io

# About/contact
author:
  name: Ben Hemingway
  url: https://benhemingway.github.io/

# plugins (formerly gems)
plugins:
  - jekyll-sitemap
# others
include: ['_pages']
markdown: kramdown
github: [metadata]