theme: jekyll-theme-cayman
# setup
title: Ben Hemingway
description: PhD Candidate in Economics, University College London
tagline: Ben Hemingway, PhD Candidate in Economics, University College London
baseurl: ""
paginate: 1

# About/contact
author:
  name: Ben Hemingway
  url: https://benhemingway.github.io/

# plugins
plugins:
  - jekyll-sitemap
# gems
gems:
  - jekyll-paginate
# others
include: ['_pages']
markdown: kramdown
