theme: jekyll-theme-cayman
# setup
title: Benjamin Hemingway
description: Research Economist, CBDC Unit, Bank of England
baseurl: ""

# repository
repository: benhemingway/benhemingway.github.io

# About/contact
author:
  name: Benjamin Hemingway
  url: https://benhemingway.github.io/

# plugins (formerly gems)
plugins:
  - jekyll-sitemap
# others
include: ['_pages']
markdown: kramdown
github: [metadata]