theme: jekyll-theme-cayman
# setup
title: Ben Hemingway
description: Ben Hemingway's Personal Webpage
tagline: Ben Hemingway's Personal Webpage
baseurl: ""
paginate: 1

# About/contact
author:
  name: Ben Hemingway
  url: https://benhemingway.github.io/

# plugins
plugins:
  - jekyll-sitemap
# gems
gems:
  - jekyll-paginate
# others
markdown: kramdown
